apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc }}
