apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  admin-password: {{ .Values.adminPassword | b64enc }}
